CREATE TABLE users (
  id             SERIAL PRIMARY KEY,
  parent_id      INTEGER NULL,
  email          VARCHAR(125) NOT NULL,
  prefix         VARCHAR(25) NULL,
  first_name     VARCHAR(50) NOT NULL,
  middle_initial VARCHAR(3) NULL,
  last_name      VARCHAR(125) NOT NULL,
  suffix         VARCHAR(25) NULL,
  status         VARCHAR(25) DEFAULT 'unconfirmed',
  type           VARCHAR(45) NOT NULL,
  perms          INTEGER NOT NULL DEFAULT '0',
  password       TEXT NOT NULL,
  created        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified       TIMESTAMP NULL,
  last_login     TIMESTAMP NULL,
  session_id     VARCHAR(128) NULL,
  referral_id    INTEGER NULL,
  otp_code       VARCHAR(6) NULL,
  otp_secret     TEXT NULL,
  otp_sent_count INTEGER NULL,
  otp_sent       TIMESTAMP NULL NULL,
  otp_verified   TIMESTAMP NULL NULL,
  autologin      VARCHAR(45) NULL,
  reg_complete   TIMESTAMP NULL,
  pass_reset     BOOLEAN NOT NULL DEFAULT '1',
  brute_force    INTEGER NOT NULL DEFAULT '0'
);
